server:
    port: 8084
spring:
    application:
        name: Config
    cloud:
        config:
          server:
            git:
              uri: https://git.oschina.net/itmuch/spring-cloud-config-repo      # ≈‰÷√Git≤÷ø‚µƒµÿ÷∑
              username:                                                         # Git≤÷ø‚µƒ’À∫≈
              password:
#Eureka
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
    instance:
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
        prefer-id-address: true
#eureka:
 # client:
  #  serviceUrl:
   #   defaultZone: http://localhost:8761/eureka/